# -*- coding: utf-8 -*-
"""AJ_TimingGuide.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15wU0z-0wlNFifHbVMAuYlfiCdLvpTQhR

# SAT/ACT Proctor Timing Guide
"""

# import statements
import pandas as pd
import numpy as np


# exported timing guide as a .csv file, hosted it on github, then read it and displayed it
df = pd.read_csv('https://raw.githubusercontent.com/AungYang/timeguideapi/main/Proctor%20Timing%20Guide_CURRENT%20-%20ALL%20Tests%20and%20Student%20Breaks%20(AM).csv')
df

#data cleaning to match with original google sheets

df.Section = df.Section.replace(['Arrive and set up for test'], ' ')
df.What = df.What.fillna('Arrive and set up for test')

#getting the relevant tests for the day

df_curr = df[(df['Test']=='PROCTOR') | (df['Test']=='ALL') | (df['Test']=='ACT') ]
df_curr

